[defaults]
# 优先使用最新的 Linux 原生 ntfs (NTFS resurrection / NTFSPlus) 驱动，替代旧的 ntfs3 和 FUSE (ntfs-3g) 驱动
ntfs_drivers=ntfs,ntfs3
ntfs_defaults=uid=$UID,gid=$GID,iocharset=utf8,prealloc
ntfs:ntfs_defaults=uid=$UID,gid=$GID,iocharset=utf8,prealloc
ntfs:ntfs_allow=uid=$UID,gid=$GID,umask,dmask,fmask,iocharset,discard,nodiscard,force,prealloc,nocase,hide_dot_files,windows_names
ntfs:ntfs3_defaults=uid=$UID,gid=$GID,iocharset=utf8,prealloc
ntfs:ntfs3_allow=uid=$UID,gid=$GID,umask,dmask,fmask,iocharset,discard,nodiscard,force,prealloc,nocase,hide_dot_files,windows_names
